import { useState } from 'react';
import { Search,Plus,History } from 'lucide-react';
import { api,formatDate } from '../../lib/api';
import { useStore } from '../../context/StoreContext';
import useApiData from '../../hooks/useApiData';
import { AdminHeading,Panel,DataState } from '../../components/AdminUI';
import { ErrorMessage,Field,Modal,Badge } from '../../components/UI';

export default function Inventory() {
  const state=useApiData('/admin/inventory'),history=useApiData('/admin/inventory/history'),{refresh}=useStore();
  const [search,setSearch]=useState(''),[low,setLow]=useState(false),[tab,setTab]=useState('stock'),[adjust,setAdjust]=useState(null),[quantity,setQuantity]=useState(''),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  if(!state.data)return <DataState {...state}/>;
  const variants=state.data.filter(v=>`${v.name} ${v.sku} ${v.size} ${v.color}`.toLowerCase().includes(search.toLowerCase())&&(!low||v.lowStock));
  function open(v){setAdjust(v);setQuantity('');setReason('');setError('');}
  async function submit(e){e.preventDefault();setBusy(true);try{await api(`/admin/inventory/${adjust.id}/adjust`,{method:'POST',body:{quantity:Number(quantity),reason}});setAdjust(null);await state.reload();await history.reload();await refresh();}catch(e){setError(e.message);}finally{setBusy(false);}}
  return <><AdminHeading title="Every size. Every colour." description="Keep your stock accurate, with a record of every adjustment."/><div className="admin-tabs"><button className={tab==='stock'?'active':''} onClick={()=>setTab('stock')}>Current stock</button><button className={tab==='history'?'active':''} onClick={()=>setTab('history')}><History size={16}/> Adjustment history</button></div>
    <Panel title={tab==='stock'?`${variants.length} active variants`:'Recent stock movements'}>{tab==='stock'?<><div className="admin-toolbar"><div className="search-input"><Search size={18}/><input aria-label="Search inventory" placeholder="Search product, size, colour or SKU…" value={search} onChange={e=>setSearch(e.target.value)}/></div><label className="checkbox-row"><input type="checkbox" checked={low} onChange={e=>setLow(e.target.checked)}/> Low stock only</label></div><div className="table-scroll"><table><thead><tr><th>Product</th><th>Variant</th><th>SKU</th><th>Stock</th><th>Availability</th><th>Action</th></tr></thead><tbody>{variants.map(v=><tr key={v.id}><td><strong>{v.name}</strong></td><td>{v.color} / {v.size}</td><td className="sku-text">{v.sku}</td><td><strong>{v.stock}</strong></td><td><Badge>{!v.stock?'Out of stock':v.lowStock?'Low stock':'In stock'}</Badge></td><td><button className="button button-outline button-small" onClick={()=>open(v)}><Plus size={15}/> Adjust</button></td></tr>)}</tbody></table>{!variants.length&&<p className="table-empty">No variants match your search.</p>}</div></>:history.data?<div className="table-scroll"><table><thead><tr><th>Product / variant</th><th>Change</th><th>Stock after</th><th>Reason</th><th>Recorded</th></tr></thead><tbody>{history.data.map(m=><tr key={m.id}><td><strong>{m.name}</strong><small>{m.color} / {m.size}</small></td><td className={m.quantity>0?'positive':'negative'}>{m.quantity>0?'+':''}{m.quantity}</td><td>{m.stockAfter}</td><td>{m.reason}{m.orderNumber&&<small>{m.orderNumber}</small>}</td><td>{formatDate(m.createdAt,true)}<small>{m.adminName||'System'}</small></td></tr>)}</tbody></table></div>:<DataState {...history}/>}</Panel>
    {adjust&&<Modal title="Adjust variant stock" onClose={()=>setAdjust(null)}><p><strong>{adjust.name}</strong><br/>{adjust.color} / {adjust.size} · Currently {adjust.stock} available</p><form onSubmit={submit}><ErrorMessage>{error}</ErrorMessage><Field label="Quantity change" hint="Positive numbers add stock. Negative numbers remove stock."><input required type="number" min="-1000000" max="1000000" value={quantity} onChange={e=>setQuantity(e.target.value)} placeholder="e.g. 10 or -2"/></Field><Field label="Reason"><input required maxLength={300} value={reason} onChange={e=>setReason(e.target.value)} placeholder="e.g. New delivery, damaged item, stock count"/></Field><p className="small-note">Expected stock after adjustment: {adjust.stock+Number(quantity||0)}</p><button className="button full-width" disabled={busy||Number(quantity)===0}>{busy?'Saving…':'Record adjustment'}</button></form></Modal>}
  </>;
}
