import { useEffect,useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Save,Plus } from 'lucide-react';
import { api } from '../../lib/api';
import { useStore } from '../../context/StoreContext';
import { AdminHeading,Panel } from '../../components/AdminUI';
import { Field,ErrorMessage } from '../../components/UI';

export default function Settings() {
  const {settings,categories,refresh,notify}=useStore(),navigate=useNavigate();
  const [form,setForm]=useState(settings),[error,setError]=useState(''),[busy,setBusy]=useState(false),[category,setCategory]=useState(''),[names,setNames]=useState({}),[password,setPassword]=useState({currentPassword:'',newPassword:''});
  useEffect(()=>{setForm(settings);},[settings]);
  const update=(key,value)=>setForm(prev=>({...prev,[key]:value}));
  async function save(e){e.preventDefault();setBusy(true);setError('');try{await api('/admin/settings',{method:'PUT',body:{...form,deliveryFee:Number(form.deliveryFee),lowStockThreshold:Number(form.lowStockThreshold)}});await refresh();notify('Shop settings saved');}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function saveCategory(id){setBusy(true);setError('');try{await api(`/admin/categories${id?`/${id}`:''}`,{method:id?'PUT':'POST',body:{name:id?names[id]:category}});setCategory('');setNames({});await refresh();notify('Category saved');}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function changePassword(e){e.preventDefault();setBusy(true);setError('');try{await api('/auth/password',{method:'POST',body:password});notify('Password updated. Sign in with your new password.');navigate('/admin/login',{replace:true});}catch(e){setError(e.message);}finally{setBusy(false);}}
  return <><AdminHeading title="Make it your own." description="Your shop details, delivery options and payment instructions."/><ErrorMessage>{error}</ErrorMessage><div className="settings-layout"><form onSubmit={save}><Panel title="Business details"><Field label="Shop name"><input required maxLength={80} value={form.shopName||''} onChange={e=>update('shopName',e.target.value)}/></Field><div className="field-pair"><Field label="Phone"><input type="tel" value={form.phone||''} onChange={e=>update('phone',e.target.value)} placeholder="2547XXXXXXXX"/></Field><Field label="WhatsApp"><input type="tel" value={form.whatsapp||''} onChange={e=>update('whatsapp',e.target.value)} placeholder="2547XXXXXXXX"/></Field></div><Field label="Email"><input type="email" value={form.email||''} onChange={e=>update('email',e.target.value)}/></Field><Field label="Shop location"><input required maxLength={300} value={form.location||''} onChange={e=>update('location',e.target.value)}/></Field></Panel>
      <Panel title="Delivery, stock & payments"><div className="field-pair"><Field label="Delivery fee (KSh)"><input required type="number" step="0.01" min="0" max="100000" value={form.deliveryFee??300} onChange={e=>update('deliveryFee',e.target.value)}/></Field><Field label="Low-stock threshold"><input required type="number" min="0" max="1000" value={form.lowStockThreshold??5} onChange={e=>update('lowStockThreshold',e.target.value)}/></Field></div><Field label="Currency"><input readOnly value="KES / KSh"/></Field><Field label="M-Pesa payment instructions" hint="Add your verified till/paybill details or instructions for contacting the shop."><textarea rows={4} maxLength={1000} value={form.mpesaInstructions||''} onChange={e=>update('mpesaInstructions',e.target.value)} placeholder="e.g. Pay to our Till… Use your order number as the reference."/></Field><p className="small-note">Payments remain pending until you verify the transaction. Automatic Daraja payment prompts can be added later.</p><button className="button" disabled={busy}><Save size={17}/>{busy?'Saving…':'Save shop settings'}</button></Panel></form>
      <div><Panel title="Categories"><div className="category-editor">{categories.map(c=><div key={c.id}><input aria-label={`Rename ${c.name} category`} maxLength={60} value={names[c.id]??c.name} onChange={e=>setNames(prev=>({...prev,[c.id]:e.target.value}))}/><button className="text-link" disabled={busy||!names[c.id]} onClick={()=>saveCategory(c.id)}>Save</button></div>)}</div><form className="add-category" onSubmit={e=>{e.preventDefault();saveCategory();}}><input required aria-label="New category name" maxLength={60} placeholder="New category…" value={category} onChange={e=>setCategory(e.target.value)}/><button className="button button-small" disabled={busy}><Plus size={16}/> Add</button></form></Panel>
        <Panel title="Admin password"><form onSubmit={changePassword}><Field label="Current password"><input required type="password" autoComplete="current-password" value={password.currentPassword} onChange={e=>setPassword(prev=>({...prev,currentPassword:e.target.value}))}/></Field><Field label="New password" hint="Use at least 12 characters."><input required minLength={12} maxLength={200} type="password" autoComplete="new-password" value={password.newPassword} onChange={e=>setPassword(prev=>({...prev,newPassword:e.target.value}))}/></Field><button className="button button-outline" disabled={busy}>Update password</button><p className="small-note">All admin sessions are signed out after a password change.</p></form></Panel></div></div></>;
}
